### ISSUE TITLE
Scanner no more recognized

### ISSUE THREAD

**Issue by akarzim** [openpaperwork/paperwork#353]
Hello,

After upgrading my Linux Mint 17 to 17.1 my scanner is no more recognized and I get this error in the terminal :

```
INFO   paperwork.frontend.util.actions Action: [Scan a single page]
INFO   paperwork.frontend.util.config Will scan using hpaio:/net/Photosmart_6520_series?ip=192.168.0.15
INFO   paperwork.frontend.util.config Will scan at a resolution of 300
MIB search path: /home/francois/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf:/usr/share/mibs/site:/usr/share/snmp/mibs:/usr/share/mibs/iana:/usr/share/mibs/ietf:/usr/share/mibs/netsnmp
Cannot find module (SNMPv2-TC): At line 10 in /usr/share/snmp/mibs/UCD-DLMOD-MIB.txt
Cannot find module (SNMPv2-SMI): At line 34 in /usr/share/snmp/mibs/UCD-SNMP-MIB.txt
Cannot find module (SNMPv2-TC): At line 37 in /usr/share/snmp/mibs/UCD-SNMP-MIB.txt

…

Cannot adopt OID in UCD-SNMP-MIB: laErrMessage ::= { laEntry 101 }
Cannot adopt OID in UCD-SNMP-MIB: laErrorFlag ::= { laEntry 100 }
Cannot adopt OID in UCD-SNMP-MIB: laLoadFloat ::= { laEntry 6 }
Cannot adopt OID in UCD-SNMP-MIB: laLoadInt ::= { laEntry 5 }
Cannot adopt OID in UCD-SNMP-MIB: laConfig ::= { laEntry 4 }
Cannot adopt OID in UCD-SNMP-MIB: laLoad ::= { laEntry 3 }
Cannot adopt OID in UCD-SNMP-MIB: laNames ::= { laEntry 2 }
Cannot adopt OID in UCD-SNMP-MIB: laIndex ::= { laEntry 1 }
WARNING paperwork.frontend.mainwindow  Exception while configuring scanner: <class 'pyinsane.rawapi.SaneException'>: <class 'pyinsane.rawapi.SaneStatus'> : Error during device I/O (9). Assuming scanner is not connected
INFO   paperwork.frontend.util.dialog Showing popup !
/usr/lib/python2.7/dist-packages/paperwork/frontend/util/dialog.py:39: PyGTKDeprecationWarning: The "flags" argument for dialog construction is deprecated. Please use initializer keywords: modal=True and/or destroy_with_parent=True. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  text=msg)
/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py:500: PyGTKDeprecationWarning: The keyword(s) "parent" have been deprecated in favor of "transient_for" respectively. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self._init(*args, **new_kwargs)
```

I also updated my kernel from 3.13.0-24 to 3.13.0-37.

Any Idea how to fix this issue ?
